---
title: "Data cleaning"
format: pdf
# see ./_quarto.yml to change other options
# (e.g., author, date (default: last time this file was edited), ...)
# these options apply to all .qmd files in the project 
# you can also change these options here
# but this will apply just to this file
---

```{r}
#| label: setup

# load packages; hide startup messages for pretty output
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(modelsummary))

# load functions
source("./src/lib/io.R")

# read data; we know the column types, so we can suppress the messages

df <- read_csv("./data/raw/data.csv", show_col_types = FALSE)
```

```{r}
#| label: tbl-data-cleaning
#| tbl-cap: Data summary

# Data transformation: convert percentages to proportions
df <- df |> mutate(
  attendance_percent = attendance_percent / 100,
  previous_scores = previous_scores / 100,
  exam_score = exam_score / 100
)

# Show summary statistics for the dataset
datasummary_skim(
  df,
  fun_numeric = list(
    Mean = Mean,
    SD = SD
  ),
  escape = FALSE
)
```

```{r}
#| label: data-write

# save data for analysis
write_csv(df, "./data/processed/data.csv")
```

